### ISSUE TITLE
Page Not Found Error

### ISSUE THREAD

**Issue by pckopat** [damalis/botble-iyzico#1]
Hello.

I installed the plugin, but when I click on the payment button, I get a 404 page not found error. What could cause this problem?

http://localhost:8888/checkout/a96b2aac11843a89db45e2d76676d930/process

**Comment by damalis** [comment]
Hello,

please, remove port 8888 then try again.

**Comment by pckopat** [comment]
> Hello,
> 
> please, remove port 8888 then try again.

The same problem continues

**Comment by pckopat** [comment]
The problem was solved when I updated the 207 lines in the HookServiceProvider file as follows.
$data['checkoutUrl'] = request()->getSchemeAndHttpHost() . "/checkout/" . $checkoutToken;

But now I encountered a different error. After the payment process, all sessions are deleted and the payment successful page does not open.

**Comment by damalis** [comment]
have you tried with razorpay payment? 

do you get same error?

**Comment by damalis** [comment]
fixed the problem.

change `'same_site' => 'lax'` to `'same_site' => null` in `./config/session.php` file.
