### ISSUE TITLE
Sandbox activation tile has incorrect data

### ISSUE THREAD

**Issue by ibrahimguzel005** [damalis/botble-iyzico#3]
Hello, when we check the sandbox activation box, it does not switch to sandbox mode. When we refresh the page, the checkbox returns to its old state.

When I check the database, payment_iyzico_mode data comes as "value". I solve the problem by manually making it 1 or 2. Can you help with this issue?

**Comment by damalis** [comment]
which botble production do you try?

**Comment by ibrahimguzel005** [comment]
Shofy ecommerce script
