### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by ibrahimguzel005** [damalis/botble-iyzico#5]
Hello,

After the payment is successful, it should normally redirect to the page indicating that the order is completed and the order information should be shown.

But when the payment is successful, we encounter a 404 warning.

Can you help us with this issue?

Website:  paurella.com

**Comment by damalis** [comment]
Where do I download FREE to try shofy production?

**Comment by ibrahimguzel005** [comment]
Hello, you can download the files whose license has been cracked from the link below. If you don't want to download it, you can try it live on my website. For example, there is an error right now.

Download: https://pixeldrain.com/u/cRGrYFab
Website link: https://paurella.com

**Comment by damalis** [comment]
Hi;

change 'same_site' => 'lax' to 'same_site' => null in `./config/session.php` file.

fixed errors and can look last modification in  [file](https://github.com/damalis/botble-iyzico/commit/1252d598a442f78bb0cd523672870db242e0abed)

**Comment by ibrahimguzel005** [comment]
Problem solved. Thank you.
