### ISSUE TITLE
Checkout City Input Error

### ISSUE THREAD

**Issue by ibrahimguzel005** [damalis/botble-iyzico#7]
Hello,

I think there will be an additional development here. There is an option in the ecommerce plugin in the Shofy script.

https://example.com/admin/ecommerce/settings/checkout
![Screenshot_12](https://github.com/damalis/botble-iyzico/assets/105642040/8fde3691-8e46-4996-9da5-07ec3bcccc69)

When we select the above option, it brings the select form type instead of input when selecting the city and state in the address information section during payment. And in this select form type, the previously defined data comes.

For example, since I have registered my address before, I have a lot of addresses and one of these addresses comes as selected. But since the iyzico plugin pays attention to the data in the add address section, when this feature is on, it cannot pull that data because that data is empty. You can see it below.
![Screenshot_15](https://github.com/damalis/botble-iyzico/assets/105642040/e5d6652e-56d1-404d-b22a-34690ee4ca2c)

But if the feature is turned off, it looks like below:
![Screenshot_14](https://github.com/damalis/botble-iyzico/assets/105642040/24e1f059-f17c-4fc3-aba5-8d0705f374f7)

Can you solve the problem here? 

I hope I have given enough information about the problem :)

**Comment by damalis** [comment]
I don't get same error and It normal work.

**Comment by ibrahimguzel005** [comment]
Did you try it with the feature I mentioned?
