### ISSUE TITLE
Class "Iyzipay\Request\CreateCheckoutFormInitializeRequest" not found

### ISSUE THREAD

**Issue by envobe** [damalis/botble-iyzico#9]
![Ekran görüntüsü 2024-08-31 154247](https://github.com/user-attachments/assets/2bbf4cdc-94e0-4b57-a8ae-65794abf4831)

Selamlar, yukarıdaki hatayı alıyorum.

Teşekkürler.

**Comment by damalis** [comment]
Merhaba;

src\Providers\HookServiceProvider.php dosyasında 26. satırda `use Iyzipay\Request\CreateCheckoutFormInitializeRequest` mevcut.

Sıfırdan tekrar kurarak deneyiniz.

iyi günler...

**Comment by envobe** [comment]
Merhaba, teşekkür ederim gayet sağlıklı çalışıyor. 

Ek olarak bir soru sormak istiyorum;

Ben debug mod True yaptım ancak panelde debugbar görünmüyor. Bunun sebebi ne olabilir? Teşekkürler.

**Comment by damalis** [comment]
Merhaba;

`APP_DEBUG=true`
`APP_ENV=developer`

.env dosyasında `developer` eklendiği zaman sorun çözülür.

iyi günler..
